<?php
/*
Copyright 2009 The Australian National University
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*******************************************************************************/

/* Define the help content for Registry Object Add tabs */
$_strings = array();

/*
 * Help Text elements: 
 * 
 * $_strings['collection_mandatory_information']
 *  -> $_strings['collection_type']
 *  -> $_strings['collection_data_source']
 *  -> $_strings['collection_group']
 *  -> $_strings['collection_key'] 
 *  -> $_strings['collection_date_accessioned']
 *  -> $_strings['collection_date_modified']
 *  -> $_strings['*']   // default content
 * 
 * $_strings['collection_names']
 *  -> $_strings['collection_name_type']
 *  -> $_strings['collection_namepart_type']
 *  -> $_strings['collection_namepart_value']
 */


$_strings['*'] = "Help text not available.";


$_strings['collection_mandatory_information'] = <<<HTMLEND
 		<span class="tabHelpTitle">Mandatory Information Tab</span><br/>
			<p class="quickLinks">
				<span class="quickLinksTitle">&raquo; Quick Links</span><br/>
					<a onClick="getHelpText('collection_type');">Collection Type</a>, 
					<a onClick="getHelpText('collection_data_source');">Data Source</a>, 
					<a onClick="getHelpText('collection_group');">Group</a>, 
					<a onClick="getHelpText('collection_key');">Key</a>, 
					<a onClick="getHelpText('collection_date_accessioned');">Date Accessioned</a>, 
					<a onClick="getHelpText('collection_date_modified');">Date Modified</a>
				</p>
				<hr/>
				<p class="helpText">
					The Mandatory Information tab is used to enter the minimum set of information that is required to create a collection record in the registry.
				</p>
				<p class="helpText">
					A collection is  
					a class of registry object that describes a grouping of physical or digital items of interest to the research community, particularly research data sets or 
					physical collections of research materials. Print publication outputs, such as theses, journal articles or books, are not within the scope of the ANDS Collections Registry.  
				</p>
				<p class="helpText">
					The Mandatory Information tab is the first tab that is shown when the Add Collection Page is loaded. You will not be able to move to another tab or save the object until all 
					fields marked with a blue asterisk have been entered.
				</p>
				<hr/>
HTMLEND;

$_strings['collection_type'] = <<<HTMLEND

			<span class="tabHelpTitle">Collection Type</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_mandatory_information');">Mandatory Information</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Yes<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Use the Collection Type field to describe the type of collection being entered.
			</p>
			<p class="helpText">
				The kind of collection (collection type) is described by choosing from the following: <br/>
				<ul>
					<li><b>catalogueOrIndex</b>: collection of resource descriptions describing the content of one or more repositories or collective works at the item level.</li>
					<li><b>collection</b>: compiled content created as separate and independent works and assembled into a collective whole for distribution and use. </li>
					<li><b>registry</b>: collection of registry objects compiled to support the business of a given community.</li>
					<li><b>repository</b>: collection of physical or digital objects compiled for information and documentation purposes and/or for storage and safekeeping. </li>
					<li><b>dataset</b>: collection of physical or digital objects generated by research activities. </li>
				</ul>			
			</p>
			<p class="helpText">
				For more information about collection types, see:<br/> 
					- <a target="_blank" href="http://www.ands.org.au/guides/defining.a.collection.html">'Defining a collection' guide</a><br/>
					- <a target="_blank" href="http://services.ands.org.au/documentation/rifcs/guidelines/collection_type_decision_tree.png">Collection Type decision tree</a>
			</p>
			<hr/>	
																
HTMLEND;


$_strings['collection_data_source'] = <<<HTMLEND

			<span class="tabHelpTitle">Data Source</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_mandatory_information');">Mandatory Information</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Yes<br/>
				<b>User Defined Value Accepted?</b> No
			</p>
			<p class="helpText">
				Use the Data Source drop down to select a data source to associate this collection with. The Data Source will, among other things, be used to control access to the record once saved in the registry.
			</p>
			<p class="helpText">
				Data Source Examples: <br/>
				<ul>
					<li>Australian National University</li>
					<li>Monash University</li>
				</ul>			
			</p>
			<hr/>	
																
HTMLEND;

$_strings['collection_group'] = <<<HTMLEND

			<span class="tabHelpTitle">Group</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_mandatory_information');">Mandatory Information</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Yes<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				A group name is generally a top level organisation, such as a university. Assign group name based on institutional affiliation. 
			</p>
			<p class="helpText">
				 Group should be described using a plain text string set to the name of the contributing organisation; for example, Australian National University. 
			</p>
			<p class="helpText">
				 For multi-institutional collections, assign a group name based on one of the institutions contributing the collections. Do no create duplicate registry objects for the same data collection.
			</p>
			<p class="helpText">
				 Group and data source are not the same thing. A data source is a harvest location for ANDS Collections Registry metadata, while a group is an assigned display and search category for <i>Research Data Australia</i> web pages. 
			</p>
			<p class="helpText">
				 A data source doesn't 'belong' to a group. One data source may contribute metadata which belongs in differing groups. Ownership or custodian responsibility is not necessarily implied.
			</p>
			<p class="helpText">
				 Group should not be confused with the Party Type of "group". Although they may have names and values in common, these concepts have different purposes in the ANDS Collections Registry.
			</p>
			
			<hr/>	
																
HTMLEND;

$_strings['collection_key'] = <<<HTMLEND

			<span class="tabHelpTitle">Key</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_mandatory_information');">Mandatory Information</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Yes<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Use the Key field to enter a primary identifier for the collection in the ANDS Collections Registry.
			</p>
			<p class="helpText">
				The key must be unique and persistent identifiers are preferred. Keys are used by ANDS to identify metadata records in the ANDS Collections Registry and for linking related metadata records. 
			</p>
			<p class="helpText">
				 A key can be any unique string. It may be, but is not required to be, a URL.  
			</p>
			<p class="helpText">
				 When you attempt to save a record with a key that exists in the ANDS Collections Registry, an overwrite warning message will be displayed. Selecting 'Yes' to this message will overwrite the existing registry record. Selecting 'No' will allow you to go back and change the key before saving the record.
			</p>			
			<p class="helpText">
				 ANDS prefers that each key should be globally unique to support discovery in federated global registries. It is recommended that all identifiers, including any identifier used as a key, be persistent i.e. of type 'doi', 'handle' or 'purl'. 
			</p>
			<p class="helpText">
				 For detailed information on persistent identifiers, see the ANDS <i>Guides on Persistent Identifiers and Digital Object Identifiers</i>, and the ANDS Guide to the <i>Identify My Data</i> product at <a target="_blank" href="http://www.ands.org.au/guides/">http://www.ands.org.au/guides/</a>
			</p>			
			<p class="helpText">
				 Additional identifiers not used as keys, including non-unique identifiers, should be stored in the Identifier element.
			</p>	
			<p class="helpText">
				<b>Defining a key</b><br/>
				The recommended approach is for content providers to mint persistent identifiers (using either the ANDS persistent identifier service or an equivalent). <br/><br/>
				Where this approach is not possible, local primary keys or identifiers may be used, although these cannot be guaranteed to be globally unique. These keys should not be changed in the local system once created. <br/><br/>
				Local keys can be enhanced by adding the server domain name or other unambiguous and unique identifier to an existing object identifier: for example, myrepo.myedu.au.mycollectionidentifier <br/><br/>
				Please contact <a href="mailto:services@ands.org.au">services@ands.org.au</a> or your ANDS liaison consultant for advice on creating keys.<br/><br/>
			</p>	
			<p class="helpText">
				<b>Key Examples</b><br/>
				An actionable (resolvable) ANDS persistent identifier: <br/>
				&lt;key&gt;http://hdl.handle.net/102.100.100/8&lt;/key&gt; <br/>
				<br/>
				An ANDS persistent identifier: <br/> 
				&lt;key&gt;hdl:102.100.100/134&lt;/key&gt; <br/> 
				<br/>
				A National Library of Australia persistent identifier: <br/>
				&lt;key&gt;http://nla.gov.au/nla.party-549576&lt;/key&gt; <br/> 
			</p>	
			<hr/>	
																
HTMLEND;

$_strings['collection_date_accessioned'] = <<<HTMLEND

			<span class="tabHelpTitle">Date Accessioned</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_mandatory_information');">Mandatory Information</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> No<br/>
				<b>User Defined Value Accepted?</b> N/A
			</p>
			<p class="helpText">
				Date accessioned records the date a collection was first registered in a managed environment such as a repository. It is an indication of the currency of a metadata record. 
			</p>
			<p class="helpText">
				 This date is the date a collection was accessioned into its source system, not the date it was registered in the ANDS Collections Registry. This date will be provided to the ANDS Collections Registry as part of a RIF-CS document. It is not derived from other data. 
			</p>
			<p class="helpText">
				 Date accessioned can only be used for registry objects that describe collections. 
			</p>
			<p class="helpText">
				 Dates are described in UTC and of one of the forms described in section 3.2.7 of the W3C's Schema Data Types document <a href="http://www.w3.org/TR/xmlschema-2/" target="_blank">http://www.w3.org/TR/xmlschema-2/</a>.  
			</p>
			<p class="helpText">
				 Dates are stored with time zone information. When a time zone is added to a UTC dateTime, the result is the date and time 'in that time zone'. For example, 2002-10-10T12:00:00+05:00 is described as 2002-10-10T07:00:00Z and 2002-10-10T00:00:00+05:00 is described as 2002-10-09T19:00:00Z.
			</p>
			<p class="helpText">
				 <b>Date Accessioned Example:</b><br/>
				 2009-12-15T01:42:04Z
			</p>
			
			<hr/>	
																
HTMLEND;


$_strings['collection_date_modified'] = <<<HTMLEND

			<span class="tabHelpTitle">Date Modified</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_mandatory_information');">Mandatory Information</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> No<br/>
				<b>User Defined Value Accepted?</b> N/A
			</p>
			<p class="helpText">
				Use the Date modified field to indicate the currency of the information in a collection record.  
			</p>
			<p class="helpText">
				 The field records the date metadata describing a collection was last changed in the source system. Only one Date modified value can be present in a metadata record at a time. 
			</p>
			<p class="helpText">
				 The presence of Date modified information means only that the metadata has changed. This might, for example, have been a change in custodian. 
				 If a dataset is continually added to, but the metadata describing it doesn't change, there is no need to record a Date modified. 
			
			</p>
			<p class="helpText">
				 On the other hand, if the underlying dataset changes its scope or nature, the metadata record describing it should change as well, and a Date modified element could be supplied to ANDS. 
			</p>
			<p class="helpText">
				 None of these scenarios affect the identification of the object or entity using a persistent identifier. Changes to the metadata record do not affect identity. 
			</p>
			<p class="helpText">
				 Dates are described in UTC and of one of the forms described in section 3.2.7 of the W3C's Schema Data Types document <a href="http://www.w3.org/TR/xmlschema-2/" target="_blank">http://www.w3.org/TR/xmlschema-2/</a>.
			</p>
			<p class="helpText">
				 Dates are stored with time zone information. When a time zone is added to a UTC dateTime, the result is the date and time 'in that time zone'. For example, 2002-10-10T12:00:00+05:00 is described as 2002-10-10T07:00:00Z and 2002-10-10T00:00:00+05:00 is described as 2002-10-09T19:00:00Z.
			</p>
			<p class="helpText">
				 <b>Date Modified Example:</b><br/>
				 2009-12-15T01:42:04Z
			</p>
			
			<hr/>	
																
HTMLEND;


$_strings['collection_names'] = <<<HTMLEND
 		<span class="tabHelpTitle">Names Tab</span><br/>
			<p class="quickLinks">
				<span class="quickLinksTitle">&raquo; Quick Links</span><br/>
					<a onClick="getHelpText('collection_name_type');">Name Type</a>, 
					<a onClick="getHelpText('collection_namepart');">Name Part</a>
				</p>
				<hr/>
				<p class="helpText">
					A name is a human-readable identifying label for a collection. Although the name element is optional it should be treated as mandatory when providing metadata to the Collections Registry.
				</p>
				<p class="helpText">
					Collection titles should be as descriptive as possible so that they are meaningful to researchers from other disciplines and in the future. Keywords included in the title are important in discovery by search engines. 'Respiration Data' or 'The Aerostar 100 Data Set' are titles that do not uniquely and comprehensively describe their objects. 'SAFARI 2000 Upper Air Meteorological Profiles, Skukuza, Dry Seasons 1999-2000' is a better title.  			
				</p>
				<p class="helpText">
					The nature of the data and other information such as the location and date range are also useful in the title, particularly if they are not recorded elsewhere in specific metadata fields for spatial and temporal coverage.
				</p>
				<p class="helpText">
					Collection titles should be unique and should not use acronyms.
				</p>
				<p class="helpText">
				<b>To record a name:</b> <br/>
				<ul>
					<li>Select a name type (whether the name to be described is the primary, alternative or abbreviated name). </li>
					<li>Use a name part element to record the name. To split a personal name into its component parts create multiple name parts. Splitting is recommended to support searching, but is not mandatory. </li>
				</ul>			
				</p>
				
				</p>
				<hr/>
HTMLEND;


$_strings['collection_name_type'] = <<<HTMLEND

			<span class="tabHelpTitle">Name Type</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_names');">Names</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Becomes mandatory field when entry is made in Name Part Value field<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Use Name type when more than one name is supplied and there is a need to distinguish between the primary name and alternative or abbreviated versions. 
			</p>
			<p class="helpText">
				There should only be one primary name. 
			</p>
			<p class="helpText">
				 The following Name Types have been identified for use in the ANDS Collection Registry:
				 <ul>
				 	<li><b>primary</b>: official name of the registry object </li>
				 	<li><b>abbreviated</b>: shortened form of, or acronym for, the official name </li>
				 	<li><b>alternative</b>: any other form of name used now or in the past as a substitute or alternative for the official name </li>
				 </ul>
			</p>
			<br/>
			<hr/>	
			
HTMLEND;


$_strings['collection_namepart'] = <<<HTMLEND

			<span class="tabHelpTitle">Name Part</span>
			<span class="quickLinks">
				in <a onClick="getHelpText('collection_names');">Names</a>
			</span>
			<p class="quickLinks">
				<span class="quickLinksTitle">&raquo; Quick Links</span><br/>
					<a onClick="getHelpText('collection_namepart_type');">Name Part Type</a>, 
					<a onClick="getHelpText('collection_namepart_value');">Name Part Value</a>
				</p>
			<hr/>
			<p class="helpText">
				Name Parts must always be used to record names; the Name element is a wrapper only.  
			</p>
			<p class="helpText">
				 All names are stored within the Name Part element, not within the &lt;name&gt; wrapper element.  
			</p>
			<p class="helpText">
				 A name can be represented by either a single Name Part (as in the case of an organisation or group) or may be split into a more granular structure through use of multiple Name Part elements. 
			</p>
			<p class="helpText">
				 Splitting a name up into its constituent parts is not mandatory.
			</p>
			<hr/>	
HTMLEND;



$_strings['collection_namepart_type'] = <<<HTMLEND


			<span class="tabHelpTitle">Name Part Type</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_namepart');">Name Part</a>
			</div>
			<hr/>
			<p class="helpText">
				 Content not available (not in spec). This is just placeholder text to fill space so that the layout doesn't break. Woohoo.
			</p>
			
			<hr/>	
HTMLEND;


$_strings['collection_namepart_value'] = <<<HTMLEND


			<span class="tabHelpTitle">Name Part Value</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_namepart');">Name Part</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Becomes mandatory field when entry is made in Name Type field<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Use this field to enter a name for the collection.
			</p>
			
			<hr/>	
HTMLEND;



$_strings['collection_identifiers'] = <<<HTMLEND

			<span class="tabHelpTitle">Identifiers Tab</span>
			<p class="quickLinks">
				<span class="quickLinksTitle">&raquo; Quick Links</span><br/>
					<a onClick="getHelpText('collection_identifier_value');">Identifier Value</a>, 
					<a onClick="getHelpText('collection_identifier_type');">Identifier Type</a>
				</p>
			<hr/>
			<p class="helpText">
				An identifier is a sequence of characters or words that uniquely identify an object within the domain of a specified authority. It may be globally unique if the specified authority has a global domain. 
			</p>
			<p class="helpText">
				 The key is a particular identifier that is unique and is used to identify the metadata record in the ANDS Collections Registry.   
			</p>
			<p class="helpText">
				 Other identifiers that are useful for discovery or re-use, or to support the functions of the metadata provider, can be recorded, even if they are not unique or persistent.  
			</p>
			<p class="helpText">
				 <b>To record an identifier</b>:
				 <ul>
				 	<li>Enter a text literal for the identifier value (max length 255 characters)</li>
				 	<li>Select an identifier type</li>
				 </ul>
			</p>
			<hr/>	
HTMLEND;

$_strings['collection_identifier_value'] = <<<HTMLEND

			<span class="tabHelpTitle">Identifier Value</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_identifiers');">Identifiers</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Becomes mandatory field when entry is made in Identifier > Type drop-down.<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Use this field to enter a text literal for the identifier.
			</p>
			<hr/>	
HTMLEND;

$_strings['collection_identifier_type'] = <<<HTMLEND

			<span class="tabHelpTitle">Identifier Type</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_identifiers');">Identifiers</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Becomes mandatory field when entry is made in Identifier > Value field<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Describe the type of identifier by either using one of the following identifier types or by defining your own type.
			</p>
			<p class="helpText">
				 Some of the identifier types in the provided vocabulary are for research domain entities, for example abn, which applies to parties. Other identifier types apply to digital objects which may be information, data or metadata.   
			</p>
			<p class="helpText">
				 <ul>
				 	<li><b>abn</b>: Australian Business Number <a href="http://www.abr.business.gov.au/(k4gdan552ohitxysv3z0wg55)/main.aspx">(link)</a></li>
				 	<li><b>arc</b>: Australian Research Council identifier -- identifiers issued by or on behalf of the Australian Research Council <a href="http://www.arc.gov.au/default.htm">(link)</a></li>
				 	<li><b>ark</b>: ARK Archival Resource Key, a persistent identifier scheme from the California Digital Library at the University of California <a href="https://confluence.ucop.edu/display/Curation/ARK">(link)</a></li>
				 	<li><b>doi</b>: Digital Object Identifier Name <a href="http://www.doi.org/index.html">(link)</a></li>
				 	<li><b>handle</b>: HANDLE System Identifier <a href="http://www.handle.net/faq.html">(link)</a></li>
				 	<li><b>infouri</b>: 'info' URI scheme -- administered by OCLC on behalf of NISO <a href="http://info-uri.info/registry/docs/misc/faq.html">(link)</a></li>
				 	<li><b>isil</b>: International Standard Identifier for Libraries and Related Organizations <a href="ttp://biblstandard.dk/isil/structure.htm">(link)</a></li>
				 	<li><b>local</b>: identifier unique within a local context. </li>
				 	<li><b>nla</b>: National Library of Australia identifier <a href="http://www.nla.gov.au/initiatives/nlapi.html">(link)</a></li>
				 	<li><b>purl</b>: Persistent Uniform Resource Locator <a href="http://purl.oclc.org/">(link)</a></li>
				 	<li><b>uri</b>: Uniform Resource Identifier -- a compact sequence of characters that identifies an abstract or physical resource <a href="http://www.ietf.org/rfc/rfc3986.txt">(link)</a></li>
				 </ul>
			</p>
			<hr/>	
HTMLEND;

$_strings['collection_subjects'] = <<<HTMLEND

			<span class="tabHelpTitle">Subjects Tab</span>
			<p class="quickLinks">
				<span class="quickLinksTitle">&raquo; Quick Links</span><br/>
					<a onClick="getHelpText('collection_subject_value');">Subject Value</a>, 
					<a onClick="getHelpText('collection_subject_type');">Subject Type</a>
				</p>
			<hr/>
			<p class="helpText">
				A subject is a term, keyword, classification code or phrase representing the primary topic or topics covered by items in the collection.  
			</p>
			<p class="helpText">
				Subject information is used to support searching.    
			</p>
			<p class="helpText">
				The suggested vocabulary for describing research domain entities and activities in the ANDS Collections Registry is the Australian and New Zealand Standard Research Classification (ANZSRC). ANZSRC is the collective name for a set of three related classifications developed for use in the measurement and analysis of research and experimental development undertaken in Australia and New Zealand. The three constituent classifications included in the ANZSRC are Type of Activity (TOA), Fields of Research (FOR), and Socio-economic Objective (SEO).   
			</p>
			<p class="helpText">
				The ANZSRC codes should be supplemented with other subject terms or keywords needed to describe the intellectual content of a collection. These may be selected from existing subject vocabularies, or alternatively, local values or keywords may be used.
			</p>
			<p class="helpText">
				All subject values and keywords are displayed and searchable and add to the findability of information in Research Data Australia. 
			</p>
			<p class="helpText">
				Subject types are displayed to provide the source authority for subject values.
			</p>
			<p class="helpText">
				 <b>To add Subjects</b>:
				 <ul>
				 	<li>Select the type of controlled vocabulary from which a term will be sourced (ANZSRC Type of Activity (TOA), Fields of Research (FOR), or Socio-economic Objective (SEO) & local)</li>
				 	<li>Then select a value from the controlled vocabulary or enter a local value</li>
				 </ul>
			</p>
			<hr/>	
HTMLEND;

$_strings['collection_subject_value'] = <<<HTMLEND

			<span class="tabHelpTitle">Subject Value</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_subjects');">Subjects</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Becomes mandatory field when entry is made in any other Subjects field<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Use the value field to select a value from a suggested vocabulary or to enter an uncontrolled term.
			</p>
			<p class="helpText">
				It is recommended that there is at least one subject from the ANZSRC classification codes Type of Activity (TOA), Fields of Research (FOR), or Socio-economic Objective (SEO). 
			</p>
			<p class="helpText">
				These classification schemes can be accessed from the Australian Bureau of Statistics web site <a href="http://www.abs.gov.au">http://www.abs.gov.au</a>, catalogue number 1297.0. The relevant code for a given research project is usually included in grant documents and is likely to be known to researchers.
			</p>
			<hr/>	
HTMLEND;

$_strings['collection_subject_type'] = <<<HTMLEND

			<span class="tabHelpTitle">Subject Type</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_subjects');">Subjects</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Becomes mandatory field when entry is made in any other Subjects field<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Use the Subject Type field to record the name of an authoritative list from which a subject term or phrase is taken or that governs its form. 
			</p>
			<p class="helpText">
				 The following subject types have been identified so far for use in the ANDS Collections Registry:    
			</p>
			<p class="helpText">
				 <ul>
				 	<li><b>anzsrc-toa</b>: Type of Activity</li>
				 	<li><b>anzsrc-for</b>: Fields of Research</li>
				 	<li><b>anzsrt-seo</b>: Socio-economic Objective</li>
				 	<li><b>local</b>: local</li>
				 </ul>
			</p>
			<p class="helpText">
				Use a type of "local" for other controlled lists not yet registered with the Library of Congress, but consider registering any lists likely to be used widely within a given community or domain.  
			</p>
			<p class="helpText">
				Use a type of "local" for uncontrolled terms such as keywords.    
			</p>
			<p class="helpText">
				<i>Local values may also be recorded for vocabularies, classification schemes or subject lists. This is not recommended. It reduces the effectiveness of searching because not all relevant records may appear in the search results list.</i> 
			</p>
			<hr/>	
HTMLEND;

$_strings['collection_descriptions'] = <<<HTMLEND

			<span class="tabHelpTitle">Descriptions Tab</span>
			<p class="quickLinks">
				<span class="quickLinksTitle">&raquo; Quick Links</span><br/>
					<a onClick="getHelpText('collection_subject_value');">Subject Value</a>, 
					<a onClick="getHelpText('collection_subject_type');">Subject Type</a>
				</p>
			<hr/>
			<p class="helpText">
				The Description element is used to record a plain text description of a collection. 
			</p>
			<p class="helpText">
				All descriptions are displayed in <i>Research Data Australia</i> except logo (work in progress). Brief descriptions display before full descriptions. Descriptions longer than 4000 characters will be truncated.
			</p>
			<p class="helpText">
				<b>Tips when recording descriptions</b>:
				 <ul>
				 	<li>To record different kinds of descriptions, repeat the description element and select a different description type. </li>
				 	<li>The difference between brief and full descriptions is not governed by formal criteria but is contextual. The same amount of storage space is provided for both kinds of description.</li>
				 </ul>
			</p>
			<p class="helpText">
				Good quality descriptions will increase the chances of a collection being discoverable through search engines.
			</p>
			<p class="helpText">		
				<b>The following principles are recommended</b>:
				 <ul>
				 	<li>Write the description for a reader who has general familiarity with a research area but is not a specialist -- this will make data more accessible for cross-disciplinary use.</li>
				 	<li>Don't use specialist acronyms or obscure jargon.</li>
				 	<li>Don't assume a reader has specialist knowledge.</li>
				 	<li>Include important keywords within the text -- this makes them accessible for search engines. Inclusion of a paragraph beginning with Keywords: and followed by a list of keywords is acceptable. However, best practice would be to include the keywords as subjects (see Subject Tab). </li>
				 	<li>Collection descriptions should be consistent with the assigned collection type. If describing a dataset, the description should be about the dataset, not just a general description of the research that created the dataset.</li>
				 	<li>Re-use of abstracts or research proposals can be a useful shortcut for a description, as long as it is appropriate to the collection being described. ANDS prefers that headings (such as 'Abstract' or 'Executive summary') not be included along with the abstract if possible.</li>
				 	<li>Include a description of the kinds of objects in the collection (for example database, printed photographs, digital images, lab notes) and the basis of selection for objects included in the collection (for example information about how data was analysed) as well as describing what the collection is about.</li>
				 	<li>Do not include hyperlinks within the description field. These will not display as links in <i>Research Data Australia</I>. Instead, include links in the Related information tab.</li>
				 </ul>
			</p>
			<p class="helpText">
				 <b>To add a description</b>:
				 <ul>
				 	<li>Enter a description for the collection in the Value field</li>
				 	<li>Select a type of description from the Type drop down or enter your own description type</li>
				 </ul>
			</p>
			<hr/>	
HTMLEND;

$_strings['collection_description_value'] = <<<HTMLEND

			<span class="tabHelpTitle">Description Value</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_descriptions');">Descriptions</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Becomes mandatory field when entry is made in any other Description field<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Use the Description Value field to enter a description of the collection.
			</p>
			<p class="helpText">
				All descriptions are displayed in <i>Research Data Australia</i> except logo (work in progress).  
			</p>
			<p class="helpText">
				Brief descriptions display before full descriptions. Descriptions longer than 4000 characters will be truncated.
			</p>
			<hr/>	
HTMLEND;

$_strings['collection_description_type'] = <<<HTMLEND

			<span class="tabHelpTitle">Description Type</span><br/>
			<div class="quickLinks" style="margin-top:4px;">
				in <a onClick="getHelpText('collection_descriptions');">Descriptions</a>
			</div>
			<hr/>
			<p class="helpText">
				<b>Mandatory?</b> Becomes mandatory field when entry is made in any other Description field<br/>
				<b>User Defined Value Accepted?</b> Yes
			</p>
			<p class="helpText">
				Use the Description Type field to record the type of description being entered.  
			</p>
			<p class="helpText">
				There are many kinds of descriptions (description types) within the research domain. The following categories have so far been identified for use in the ANDS Collections Registry: 
			</p>
			<p class="helpText">
				 <ul>
				 	<li><b>brief</b>: short account for selection purposes</li>
				 	<li><b>full</b>: full account</li>
				 	<li><b>logo</b>: symbol used as an identifying mark</li>
				 	<li><b>note</b>: a brief informational message, not object metadata, to notify the record consumer of some important aspect regarding the object or its metadata</li>
				 	<li><b>rights</b>: information about rights held in and over the collection such as copyright, licenses and other intellectual property rights</li>
				 	<li><b>accessRights</b>: information about access rights to the collection or service, including access restrictions based on privacy, security, or other policies</li>
				 </ul>
			</p>
			<p class="helpText">
				Local description types may also be used. These may be appropriate for recording important descriptive elements from the source metadata which are not present in RIF-CS, but which are essential to add context to the metadata.  
			</p>
			<hr/>	
HTMLEND;



